### ISSUE TITLE
Create basic game-board

### ISSUE THREAD

**Issue by seanvail** [Seanv554/leapmotion_boardgame#2]
Create class that generates a board of N x N squares of two alternating materials. 
- Class will have accessor method that contains a 2D array of pointers to each individual square.
- Each square on the board stores a (possibly null) reference to a game-piece that may or may not be present

**Comment by seanvail** [comment]
As we further our understanding of how the game-pieces, game-board, and leapmotion actor will interact, please note down requests for getters/setters or other tweaks needed in regards to the game-board here.

**Comment by deanljohnson** [comment]
I can think of two functions we would want on the board:

GetCenter: Returns the center of a certain square. Will need this to snap game pieces to. This might be better on the square class.
GetSquareBelow: Returns a pointer to the square below a certain point. Will need this to snap game pieces to, and to give the user feedback on what square they are about to place their piece in.

**Comment by seanvail** [comment]
Okay, both of those methods should be doable.

Update on my current progress: I must admit that my C++ skills are very rough around the edges and I'm still learning how to use UE4 in C++.
Right now I'm still trying to make a method (ideally called when the game starts) that spawns an N x N grid of BoardSquare actors and stores references to all the spawned actors. Any relevant tutorials someone can point out?

**Comment by deanljohnson** [comment]
I've been using blueprints mostly, but I would try a kind of hybrid approach. Create a dummy, mostly empty, actor blueprint in the editor. Then have it extend a c++ actor that you create. In the c++, override BeginPlay:

``` cpp
//in MyActor.h
//Might have this syntax a bit off
UClass()
class MyActor : public Actor
{
  GENERATED_BODY();
  BoardSquare *m_Squares[];
public:
// Called when the game starts or when spawned
  virtual void BeginPlay() override;
}

//in MyActor.cpp
void MyActor::BeginPlay()
{
  //Create the BoardSquare's here. You'll probably want to make them children of the board.
}
```

**Comment by seanvail** [comment]
Okay, after getting frustrated and taking a break it is becoming more clear to me what I must do. I made a child blueprint of my class and figured out how to spawn it. Now I'm working on spawning a 2D array of them, shouldn't be too hard once I figure out why Actor::GetActorBounds() isn't compiling (probably a casting issue).

**Comment by seanvail** [comment]
Okay, got a 2D array of these squares spawning side-by-side, finally have some momentum here. Up until now I've been working in a separate project, gonna work on migrating the blueprints and code over to this project and push what I got so far into another branch, I will continue working on this throughout the week.

**Comment by seanvail** [comment]
Latest challenge: Changing a static mesh's material at runtime in the C++ code, I've tried several implementations so far that either don't work or cause UE4 to crash. Gonna continue this tomorrow.

**Comment by deanljohnson** [comment]
With your game board are you implementing the Checker's rules or just the basic board shape / piece placement / etc?

**Comment by seanvail** [comment]
For now I am only implementing the basic board shape and piece placement mechanisms. Once I perfect that, game rules should be easy to code.

Sorry about the lack of commits, I have some progress on my local copy but I've been bogged down with work in CS-157B. After I get my midterm and assignment done this week I will redirect my focus back onto this project.

**Comment by deanljohnson** [comment]
I worked on some of the basic Checkers rules. I had some time without much else to do, so I wrote some of the basic rules, just to validate moves essentially. You could easily use this as a base class for whatever else you do, or just copy/paste some things I wrote. I'll probably be committing these a little later today.

**Comment by deanljohnson** [comment]
Here's some info on the interface I've been writing the game rules to so far:

For Pieces:
GetIndex - returns a 2 element array with an x/y index on the board
SetIndex - takes a 2 element array with an x/y index on the board, sets it on the piece so the piece tracks it's position. I don't intend for this to move the piece, but just as a way to track the info on the pieces themselves
IsBlack - returns a bool for whether or not the piece is black.
IsKing - Same as above, but for is this piece a king.

The blueprint I am making is only going to say whether a certain move is valid and conforms to the games rules - the actual movement should happen in your classes/blueprints since they track the piece locations and such. To that end, my Blueprint is going to have a reference to a GameBoard interface with these methods:
PieceAtIndex - returns the piece at the given index, or nothing if it is empty
IndexIsOccupied - bool for whether or not there is a piece at a given index
CapturePiece - captures the given piece. My code will make sure it is of the enemy color.

My function CanMovePiece takes a piece and the target index and will return a bool saying whether or not the move can be made, and could set the index of the piece being moved if you want. It's a minor change either way.

I have some more work to do so I plan to commit my stuff tomorrow morning. Things don't have to mesh up perfectly - we can fix any differences on Thursday.

**Comment by deanljohnson** [comment]
Committed the rules blueprint. It has a method CanMovePiece with 3 arguments - a CheckersPiece (interface I committed), Index (This is the target move position), and a GameBoard (also an interface I committed). My blueprint does the following:

Checks to make sure movement is diagonal - if not return false, else continue
Makes sure movement is in the right direction vertically, based on color and if the piece is a king. By convention, I'm saying that black starts on the side of the board with lower y-indices and moves to higher indices, unless they are a king.
If movement is a 1 step diagonal, and the target is open, return true
If movement is 2 step diagonal, target is open, and there is an enemy piece in the middle of the movement, call CapturePiece with the enemy piece as an argument, and return true, else return false

My blueprint does not check that the target index is on the board currently, because that requires more awareness of the whole board than I think appropriate in this method. If it would be easier, I could easily add it.

I also do not make a piece a king if it reaches the end of the board, but that could also be added pretty easily.

**Comment by deanljohnson** [comment]
Alright, I've gotten quite a bit done today, and here's a summary:

The Game Board:
- Renamed from BoardSpawner to Board. Makes the implementation a lot simpler if this counts as a board, and with the new functionality I've added the name is more appropriate. The board spawning code is called from BeginPlay
- Spawns squares, with proper coloring, and as children of itself
- Stores the Squares, and has methods to get the center of a square given an index, and to determine if a given index is a black square.
- The material for the two board colors, and the number of squares per side, is now configurable in the editor. So, if we ever wanted to change the size/colors of a board, it is now really easy.

CheckersBoard:
- extends Board to add checkers specific functionality. Not fully implemented yet, but does spawn pieces in the appropriate places, and sets their color (see below).

CheckersPiece:
- extends GenericPiece
- When spawned, you can set whether or not it is black, and it will set it's material as needed.

If you pull the repo and hit play, you should see a properly colored board with properly colored pieces in their proper places! We are getting somewhere.

The next step is to start working on moving pieces while obeying the rules of Checkers. The project could probably do with some cleaning up as well - renaming assets, comments, adjusting directory structure, consistent design, etc.

Since we might be working on similar things, be sure to commit and push your work often and to pull from origin/master before commits/pushes. That way we don't end up doing hours of work just to have someone else commit similar work. If we have edited the same file, I'd just rename the local version, pull the remote, compare and merge changes, quick email to coordinate, and then commit and push. Hopefully we can start making some good progress.

**Comment by seanvail** [comment]
Nice work! Looking forward to diving into the new features!

**Comment by deanljohnson** [comment]
Since it seems like the only things left to do with game boards are game specific, I think the basic game board is finished and I think we can close this issue.
